### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by itssiggi** [marzzzello/pytr#15]
**Description of the bug**
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/pytr", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/pytr/main.py", line 129, in main
    dl = DL(login(web=weblogin), args.output, args.format, since_timestamp=since_timestamp)
  File "/opt/homebrew/lib/python3.9/site-packages/pytr/account.py", line 77, in login
    for remaining in range(countdown):
TypeError: 'float' object cannot be interpreted as an integer
```

I receive the error message above while trying to log in. I am entering nothing as "code" since I didn't receive a notification on my mobile device. Older versions used to work.

```
pytr login
```

**Environment**
 - OS: MacOS 12.0.1
 - Version: 0.0.13

**Comment by C0D3D3V** [comment]
If web login does not work for you, you can also use the old login that simulates the app, with the option `--applogin`.

**Comment by itssiggi** [comment]
The issued was solved by updating the app to the latest version. But maybe others encounter the same problem.
