### ISSUE TITLE
web session remains open - working with multiple accounts not possible

### ISSUE THREAD

**Issue by britiscurious** [marzzzello/pytr#20]
**Description of the bug**
I'm trying to download documents from two different Trade Republic accounts.
But the web session for the first account remains active and it is not possible to retrieve documents from the second account afterwards.

**To Reproduce**

1. run `pytr dl_docs --last_days 180 .`
2. Enter the TradeRepbulic phone number for the **first** account.
3. Enter the TradeRepbulic pin for the **first** account.
4. Do **not** save credentials. 

Log confirms: 

> hh:mm:ss Credentials not saved

Documents for the first account are downloaded properly.

5. run `pytr dl_docs --last_days 180 .` again
6. Enter the TradeRepbulic phone number for the **second** account.
7. Enter the TradeRepbulic pin for the **second** account.
8. Do **NOT** save credentials.

Log says:

> hh:mm:ss Credentials not saved
> hh:mm:ss Web session resumed
> hh:mm:ss Logged in

The log give the impression, that the login to the second account was successful. But actually you get or remain logged in into the first account. So documents from the second account are **not** downloaded. Instead documents from the **first** account are downloaded again.

**Expected behavior**
An existing web session gets closed, when pytr gets called with different credentials.
Login into the second Trade Republic account actually happens and documents from the second Trade Republic account are downloaded.

**Error log**
n.a.

**Environment**

- OS: MacOS 12.1
- pytr version: 0.0.18

**Additional context**
n.a.

**Comment by britiscurious** [comment]
Workaround:

Remove `~/.pytr/cookies.txt` after documents from the first account have been downloaded.

**Comment by marzzzello** [comment]
Mh yeah, the cookies shouldn't be saved then
