### ISSUE TITLE
Permission error for export_transactions

### ISSUE THREAD

**Issue by Johannes0941** [marzzzello/pytr#26]
**Description of the bug**
When calling the export_transactions function, I get a permission denied error.
Probably the input and ouput should be something else. Could you please clearify that and maybe add it in the code documentation.
Thank you very much!

**Error log**

```
(base) C:\Users\49176\Documents\trade_republic>pytr export_transactions C:\Users\49176\Documents\trade_republic C:\Users\49176\Documents\trade_republic
Traceback (most recent call last):
  File "C:\Users\49176\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\49176\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\49176\anaconda3\Scripts\pytr.exe\__main__.py", line 7, in <module>
  File "C:\Users\49176\anaconda3\lib\site-packages\pytr\main.py", line 168, in main
    export_transactions(args.input, args.output, args.lang)
  File "C:\Users\49176\anaconda3\lib\site-packages\pytr\utils.py", line 174, in export_transactions
    with open(input_path, encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\49176\\Documents\\trade_republic'
```

After calling the function I added the folder previously generated by dl_docs and the same folder, to save the document there.
Are these principally the right steps?

**Comment by C0D3D3V** [comment]
try to use it like: `pytr export_transactions C:\Users\49176\Documents\path\to\other_events.json C:\Users\49176\Documents\export\path\to\results.csv`

**Comment by Johannes0941** [comment]
Thank you! Now I understood what the function does. 
However I found that dl_docs already creates such a file, so maybe dl_docs should be positioned a bit clearer, as it seems to me this would be the most important function for most Parquet/ Portfolio Performance users. Also I guess you need to download the docs anyway before being able to export the transactions, so maybe the extended functionality of dl_docs made this method obsolete?

In my initial understanding the method would have created a method of all buy and sell actions of stocks directly, but now when reading the description I understand that it only considers bank transerfs to the account.

But as Parquet has a very good batch importing of pdf´s, this missing funtionality was not really a problem after all.
