### ISSUE TITLE
pytr dl_docs is throwing error and cannot complete 

### ISSUE THREAD

**Issue by alexw1982** [marzzzello/pytr#3]
I tried running pytr today again to download my latest documents but I repeatedly get the following error message:

```
Received error message: '27 E {"errors":[{"errorCode":"UNKNOWN_ERROR","errorField":null,"errorMessage":"Unknown error","meta":{"source":"PLATFORM"}}]}'
Traceback (most recent call last):
  File "/home/alex/.local/bin/pytr", line 8, in <module>
    sys.exit(main())
  File "/home/alex/.local/lib/python3.8/site-packages/pytr/main.py", line 135, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/alex/.local/lib/python3.8/site-packages/pytr/dl.py", line 28, in dl_loop
    _subscription_id, subscription, response = await self.tr.recv()
  File "/home/alex/.local/lib/python3.8/site-packages/pytr/api.py", line 246, in recv
    raise TradeRepublicError(subscription_id, subscription, payload)
pytr.api.TradeRepublicError: ('27', {'type': 'timelineDetail', 'id': '97ab309c-3101-45da-98f7-36d92172e041'}, {'errors': [{'errorCode': 'UNKNOWN_ERROR', 'errorField': None, 'errorMessage': 'Unknown error', 'meta': {'source': 'PLATFORM'}}]})
```

**Comment by fsdjfhadflkjhsd** [comment]
I just had the same problem. Looks like TR changed something.

**Comment by nPyRoX** [comment]
Unfortunately, I am receiving the same problem :-(

**Comment by ffeldmann** [comment]
My guess is that the Header: [_default_headers = {"User-Agent": "TradeRepublic/Android 24/App Version 1.1.2875"}](https://github.com/marzzzello/pytr/blob/ace1abe3a4efd688bfd3652fabaf971170e36fcb/pytr/api.py#L43) is somehow outdated and needs an update. I do not know which Android Version/iOS can be used here, anyone an idea how to retrieve it?

**Comment by marzzzello** [comment]
It is not the user agent header but I updated them anyway.
I published a new version which will not fail at this error but it is not really fixed yet.
With the new version it is also possible to modify the filenames (see `pytr dl_docs -h`)

**Comment by fsdjfhadflkjhsd** [comment]
> It is not the user agent header but I updated it anyway.
> I published a new version which will not fail at this error but it is not really fixed yet.
> With the new version it is also possible to modify the filenames (see `pytr dl_docs -h`)
> Closed for now (reopen if there are still problems)

Thanks a lot! I just tested it and the download worked like a charm.
