### ISSUE TITLE
export_transactions is an invalid command

### ISSUE THREAD

**Issue by brunomorampc** [marzzzello/pytr#30]
First of all thanks for the great tool.

I would like to dowload the csv files to import it to portfolio performance. But the command `export_transactions` seems to be not available anymore. How can I do that? Thanks

**Comment by C0D3D3V** [comment]
```
pytr  export_transactions --help
usage: pytr export_transactions [-h] [-l LANG] INPUT OUTPUT

Create a CSV with the deposits and removals ready for importing into Portfolio
Performance

positional arguments:
  INPUT                 Input path to JSON (use other_events.json from dl_docs)
  OUTPUT                Output path of CSV file

options:
  -h, --help            show this help message and exit
  -l LANG, --lang LANG  Two letter language code or "auto" for system language (default:
                        auto)
```

**Comment by brunomorampc** [comment]
thanks but the problem was that the export_transactions was not even existing as an option.
I figure it out that the problem was the python version. I had download a old version of pytr.

thank you :) you can close the issue
