### ISSUE TITLE
Provide pre-build binaries

### ISSUE THREAD

**Issue by yubiuser** [marzzzello/pytr#59]
Thanks for creating `pytr`!

I'm using it on linux and was not keen to setup a whole Python environment to install `pytr`. Therefore, I created a Docker image that will build `pytr` from where I can export the binary. I tweaked it to run on Github action where it will attach the binaries to every release. You can find the repo at https://github.com/yubiuser/pytr-binary and the binaries at https://github.com/yubiuser/pytr-binary/releases/tag/v1.0.0.

I could file a PR at this repo to use the same action/Dockerfile so that you could also attach binaries to your releases (you would need to start using releases, not tags-only). Let me know if you are interesting.

**Comment by marzzzello** [comment]
On Linux a python environment is usually ready with one command like `pacman -S python-pipx`.
Updates are also installed with one command. There is no need to go to GitHub and manually download each new release.
I can't really see the benefit of binary releases here but of course you can do it for yourself
