### ISSUE TITLE
Phone No and Pin arguments are ignored when credentials file exists

### ISSUE THREAD

**Issue by johannespartin** [marzzzello/pytr#8]
**Description of the bug**
When running pytr with -n/--phone_no and -p/--pin arguments and the credential file exists, those arguments will be ignored and the values in the credentials file will be used. 
This is an issue, as the user does not receive any info about the arguments not being used and he has to delete the credentials file manually if login data changes (or was stored with wrong values). 

**To Reproduce**
1. Login with pytr
2. Try to login with different credentials with specific arguments
3. Login uses old credentials (even if they are wrong)

**Expected behavior**
Two options: 
1. always prefer arguments 
2. print that credentials file exists in ~/.pytr/credentials and offer an option to remove cached credentials in the CLI

**Environment**
 - OS: Mac
 - Version: 0.0.8

**Comment by marzzzello** [comment]
Thanks for you bug report. It should be fixed in the new release
