### ISSUE TITLE
dl_docs: error: the following arguments are required: PATH 

### ISSUE THREAD

**Issue by DanielGuo1** [marzzzello/pytr#9]
**Description of the bug**
Thanks for the great work. I used the tool for the first time today. Login, portfolio and the other functions work perfectly. I only get the error message for the dl_docs:

**Error log**
```
(virtualenv) C:\Users\guowe\PycharmProjects\traderepublic>pytr dl_docs
usage: pytr dl_docs [-h] [--format FORMAT_STRING] [--last_days DAYS] PATH
pytr dl_docs: error: the following arguments are required: PATH
```

**Environment**
 - OS: Windows
 - Version: 11
 -  Python: 3.10

Thanks a lot for the work! Do you need more information regarding the error log?

**Comment by marzzzello** [comment]
You need to specify a path or directory as argument:
```
pytr dl_docs foldername
```
